version: '3'

services:
  # Application

  database:
    image: 'postgres'
    container_name: 'postgres-${APP_NAME}'
    restart: always
    ports:
      - '${DATABASE_PORT}:5433'
    environment:
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_ROOT_PASSWORD=${DATAVASE_ROOT_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  redis:
    image: 'bitnami/redis'
    container_name: 'redis-${APP_NAME}'
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
